services:
  pressmint_ocr_comparisons:
    build: .
    command: jupyter lab --allow-root --ip='*' --NotebookApp.token='' --NotebookApp.password=''
    ports:
      - 8888:8888
    working_dir: /veld/code/
    volumes:
      - ./src/:/veld/code/
      - ./data/jupyter/:/veld/storage/jupyter/
      - ./data/:/data/

